site: 
  data:
    lat: 45.00 
    lon: -93.00 
    # elev: 1099
    year: 2013
    # tz: -6
    site_boundaries: 
      verts:  
        - [0.0, 0.0]
        - [0.0, 20000.0]
        - [20000.0, 20000.0]
        - [20000.0, 0.0] 
      verts_simple: 
        - [0.0, 0.0]
        - [0.0, 20000.0]
        - [20000.0, 20000.0]
        - [20000.0, 0.0]
  solar_resource_file: ""
  wind_resource_file: ""
  wave_resource_file: ""
  grid_resource_file: ""
  hub_height: 115.0
  capacity_hours: []
  desired_schedule: []
  curtailment_value_type: "grid" #"desired_schedule" #NOTE: will be updated to interconnect_kw
  solar: true
  wind: true
  wave: false
  wind_resource_origin: "WTK"
  renewable_resource_origin: "HPC" #[API or HPC]
  

technologies:
  wind:
    num_turbines: 60 #216
    turbine_rating_kw: 6000.0
    rotor_diameter: 170
    # hub_height: 115
    model_name: floris
    timestep: [0, 8760]
    floris_config: input/library/wind/floris_generic_input.yaml
    fin_model: !include default_fin_config.yaml
    operational_losses: 12.83
  pv:
    system_capacity_kw: 482400 #kWdc
    dc_degradation: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    fin_model: !include default_fin_config.yaml
    panel_system_design: !include PV_UtilitySystemDesign_ATB2024.yaml
    panel_tilt_angle: "lat-func"
    dc_ac_ratio: 1.34
    losses: 14.0757 #dc losses
    inv_eff: 96
  battery:
    system_capacity_kwh: 400000
    system_capacity_kw: 100000
    minimum_SOC: 20.0
    maximum_SOC: 100.0
    initial_SOC: 20.0
    fin_model: !include default_fin_config.yaml
  grid:
    interconnect_kw: 720000 # Set higher than rated generation capacity
    fin_model: !include default_fin_config.yaml

config:
  simulation_options:
    wind:
      skip_financial: false
  dispatch_options:
    battery_dispatch: load_following_heuristic # load_following_heuristic #heuristic
    solver: cbc
    n_look_ahead_periods: 48
    grid_charging: false
    pv_charging_only: false
    include_lifecycle_count: false
  cost_info: # Costs from GS Manuscript Supplemental Table S11
    wind_installed_cost_mw: 1228000 # (2022USD) 
    solar_installed_cost_mw: 779104 # (2022USD) 
    storage_installed_cost_mwh: 246000 # (2022USD) 
    storage_installed_cost_mw: 317000 # (2022USD) 
    wind_om_per_kw: 29.0 # (2022USD) 
    pv_om_per_kw:  13.43 # (2022USD) 
    battery_om_per_kw: 33 # (2022USD) based on 0.025 percent of battery capex with a 100MW 1hr battery
